# docker-compose --version
# Samakan versi nya!
version: '3.3'

services:
  app:
    build: .
    container_name: node_app
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}

# services:
#   app:
#     build: .
#     container_name: node_app
#     restart: always
#     env_file:
#       - .env
#     ports:
#       - "4000:4000"
#     depends_on:
#       - db
#     environment:
#       DB_HOST: ${DB_HOST}
#       DB_USER: ${DB_USER}
#       DB_PASS: ${DB_PASSWORD}
#       DB_NAME: ${DB_NAME}
#       JWT_SECRET: ${JWT_SECRET}

#   db:
#     image: mysql:8.0
#     container_name: mysql_db
#     restart: always
#     env_file:
#       - .env
#     ports:
#       - "3000:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_DATABASE: ${DB_NAME}
  
# # Hapus aja jika tidak digunakan
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     container_name: phpmyadmin
#     restart: always
#     depends_on:
#       - db
#     ports:
#       - "2024:80"
#     environment:
#       PMA_HOST: db
#       # PMA_USER: ${DB_USER}
#       # PMA_PASSWORD: ${DB_PASSWORD}

# volumes:
#   mysql_data:
